# Generated by Django 2.0 on 2017-12-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BracketsOJ', '0003_auto_20171220_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judge_job',
            name='submission',
        ),
        migrations.AddField(
            model_name='submission',
            name='code',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='judge_job',
        ),
    ]
