# Generated by Django 2.0 on 2017-12-24 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BracketsOJ', '0004_auto_20171224_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BracketsOJ.contest'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='judged',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='memory',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(blank=True, choices=[('AC', 'Accepted'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('WA', 'Wrong Answer'), ('RTE', 'Run Time Error')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
