# Generated by Django 2.0 on 2017-12-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BracketsOJ', '0005_auto_20171224_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='judged',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(blank=True, choices=[('AC', 'Accepted'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('WA', 'Wrong Answer'), ('RTE', 'Run Time Error'), ('QU', 'In queue')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
