# Generated by Django 2.0 on 2017-12-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BracketsOJ', '0007_auto_20171227_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='last_submit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
