# Generated by Django 2.0 on 2017-12-27 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BracketsOJ', '0008_userinfo_last_submit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='contest',
        ),
        migrations.AddField(
            model_name='submission',
            name='problem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BracketsOJ.problem'),
            preserve_default=False,
        ),
    ]
