# Generated by Django 2.0 on 2017-12-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BracketsOJ', '0009_auto_20171227_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='score',
        ),
        migrations.AddField(
            model_name='problem',
            name='checker',
            field=models.CharField(default='ecmp', max_length=50),
        ),
    ]
