# Generated by Django 2.0 on 2017-12-27 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BracketsOJ', '0010_auto_20171227_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved', models.IntegerField(default=0)),
                ('last_submission', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_score',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BracketsOJ.contest'),
        ),
        migrations.AddField(
            model_name='user_score',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
