# Generated by Django 2.0 on 2017-12-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BracketsOJ', '0011_auto_20171227_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(blank=True, choices=[('AC', 'Accepted'), ('TL', 'Time Limit Exceeded'), ('ML', 'Memory Limit Exceeded'), ('WA', 'Wrong Answer'), ('RTE', 'Run Time Error'), ('QU', 'In queue'), ('CE', 'Syntax error')], max_length=50, null=True),
        ),
    ]
