# Generated by Django 2.0 on 2017-12-28 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BracketsOJ', '0012_auto_20171228_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_score',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='user_score',
            name='user',
        ),
        migrations.DeleteModel(
            name='user_score',
        ),
    ]
