# Generated by Django 2.0 on 2017-12-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BracketsOJ', '0013_auto_20171228_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='input_section',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='problem',
            name='output_section',
            field=models.CharField(max_length=500),
        ),
    ]
