# Generated by Django 2.0 on 2018-01-01 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BracketsOJ', '0015_auto_20180101_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='rate',
        ),
    ]
